name: Kick Off Container Scanning

on:
  workflow_dispatch

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: |
          echo "Building Docker Container to Release the Application"

  scan-container:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Submit Veracode Container Scan
        env:
          VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
          VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode scan --source alpine:latest --type image	--format table
      
  release-container:
    needs: scan-container
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: |
          echo "Send Container to Registry"
