name: Kick Off Container Scanning

on:
  workflow_dispatch

jobs:
  scan-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Veracode Container Scan
        env:
          VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
          VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode scan
          echo "hello world"
      
