name: Kick Off Container Scanning

on:
  workflow_dispatch

jobs:
  scan-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Veracode Container Scan
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode version
          echo "hello world"
      
